import dotenv from 'dotenv';
dotenv.config();
import { createRecipe, closeDb } from './store';

const recipes = [
    {
        name: 'Jollof Rice',
        category: 'Main Course',
        description: 'The iconic West African one-pot rice dish cooked in a rich tomato and pepper sauce. A staple at every Nigerian celebration.',
        servings: 6,
        prepMins: 20,
        cookMins: 60,
        difficulty: 'medium' as const,
        ingredients: [
            { name: 'Long grain parboiled rice', quantity: '3', unit: 'cups' },
            { name: 'Tomatoes', quantity: '4', unit: 'large' },
            { name: 'Red bell pepper (tatashe)', quantity: '2', unit: 'large' },
            { name: 'Scotch bonnet pepper (atarodo)', quantity: '2', unit: 'pieces', notes: 'Adjust to taste' },
            { name: 'Onion', quantity: '2', unit: 'large' },
            { name: 'Chicken stock', quantity: '2', unit: 'cups' },
            { name: 'Tomato paste', quantity: '2', unit: 'tbsp' },
            { name: 'Vegetable oil', quantity: '4', unit: 'tbsp' },
            { name: 'Seasoning cubes', quantity: '2', unit: 'pieces' },
            { name: 'Salt', quantity: '1', unit: 'tsp', notes: 'To taste' },
            { name: 'Curry powder', quantity: '1', unit: 'tsp' },
            { name: 'Thyme', quantity: '1', unit: 'tsp' },
            { name: 'Bay leaves', quantity: '2', unit: 'pieces' },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Blend tomatoes, red bell peppers, scotch bonnet, and one onion until smooth.' },
            { stepNumber: 2, instruction: 'Heat oil in a large pot. Fry tomato paste for 2 minutes, then add the blended tomato mix.' },
            { stepNumber: 3, instruction: 'Cook the tomato sauce on medium heat, stirring frequently, until the oil floats to the top — about 20 minutes.' },
            { stepNumber: 4, instruction: 'Add chicken stock, seasoning cubes, curry, thyme, bay leaves, and salt. Bring to a boil.' },
            { stepNumber: 5, instruction: 'Wash the rice until water runs clear. Add to the pot and stir well.' },
            { stepNumber: 6, instruction: 'Reduce heat to low, cover tightly, and cook for 30 minutes. Check and stir every 10 minutes.' },
            { stepNumber: 7, instruction: 'Once rice is cooked and sauce absorbed, taste and adjust seasoning. Serve hot.' },
        ],
    },
    {
        name: 'Egusi Soup',
        category: 'Soup',
        description: 'A rich and hearty Nigerian soup made with ground melon seeds, leafy greens, and assorted meats. Best served with pounded yam or eba.',
        servings: 6,
        prepMins: 30,
        cookMins: 50,
        difficulty: 'medium' as const,
        ingredients: [
            { name: 'Ground egusi (melon seeds)', quantity: '2', unit: 'cups' },
            { name: 'Assorted beef (shaki, ponmo)', quantity: '500', unit: 'g' },
            { name: 'Stockfish', quantity: '200', unit: 'g' },
            { name: 'Smoked fish', quantity: '200', unit: 'g' },
            { name: 'Spinach or pumpkin leaves (ugwu)', quantity: '300', unit: 'g' },
            { name: 'Palm oil', quantity: '4', unit: 'tbsp' },
            { name: 'Crayfish (ground)', quantity: '2', unit: 'tbsp' },
            { name: 'Onion', quantity: '1', unit: 'large' },
            { name: 'Scotch bonnet pepper', quantity: '2', unit: 'pieces' },
            { name: 'Seasoning cubes', quantity: '2', unit: 'pieces' },
            { name: 'Salt', quantity: '1', unit: 'tsp', notes: 'To taste' },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Wash and cook the assorted meats and stockfish with onion, seasoning cubes, and salt until tender. Reserve the stock.' },
            { stepNumber: 2, instruction: 'Mix ground egusi with a little water to form a thick paste.' },
            { stepNumber: 3, instruction: 'Heat palm oil in a pot. Fry diced onion and blended pepper for 5 minutes.' },
            { stepNumber: 4, instruction: 'Add egusi paste in small clumps. Fry on medium heat, turning occasionally, for 10 minutes until lightly browned.' },
            { stepNumber: 5, instruction: 'Add the cooked meats, stockfish, smoked fish, crayfish, and enough stock to thin the soup.' },
            { stepNumber: 6, instruction: 'Simmer for 15 minutes. Add pumpkin leaves and cook for 3 more minutes.' },
            { stepNumber: 7, instruction: 'Adjust seasoning and serve with pounded yam, eba, or fufu.' },
        ],
    },
    {
        name: 'Suya',
        category: 'Snack / Street Food',
        description: 'Spiced grilled beef skewers — Nigeria\'s most popular street food. Marinated in a peanut-based spice blend called yaji.',
        servings: 4,
        prepMins: 20,
        cookMins: 20,
        difficulty: 'easy' as const,
        ingredients: [
            { name: 'Beef sirloin or flank steak', quantity: '600', unit: 'g' },
            { name: 'Roasted groundnuts (finely ground)', quantity: '4', unit: 'tbsp' },
            { name: 'Paprika', quantity: '1', unit: 'tsp' },
            { name: 'Ginger powder', quantity: '1', unit: 'tsp' },
            { name: 'Garlic powder', quantity: '1', unit: 'tsp' },
            { name: 'Onion powder', quantity: '1', unit: 'tsp' },
            { name: 'Cayenne pepper', quantity: '1', unit: 'tsp', notes: 'Adjust to heat preference' },
            { name: 'Salt', quantity: '1', unit: 'tsp' },
            { name: 'Vegetable oil', quantity: '2', unit: 'tbsp' },
            { name: 'Onion rings (to serve)', quantity: '1', unit: 'large' },
            { name: 'Tomatoes (to serve)', quantity: '2', unit: 'medium' },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Slice beef thinly across the grain into long flat strips about 5mm thick.' },
            { stepNumber: 2, instruction: 'Mix ground peanuts, paprika, ginger, garlic, onion powder, cayenne, and salt to make the yaji spice blend.' },
            { stepNumber: 3, instruction: 'Coat beef strips thoroughly in the yaji mixture. Add oil and mix well. Marinate for at least 30 minutes.' },
            { stepNumber: 4, instruction: 'Thread marinated beef onto skewers.' },
            { stepNumber: 5, instruction: 'Grill on high heat for 8–10 minutes per side until charred at edges but still juicy.' },
            { stepNumber: 6, instruction: 'Serve with fresh onion rings, sliced tomatoes, and extra yaji sprinkled on top.' },
        ],
    },
    {
        name: 'Pounded Yam',
        category: 'Swallow',
        description: 'A smooth, stretchy Nigerian swallow made from boiled yam pounded until lump-free. Traditionally served with soups like egusi or okra.',
        servings: 4,
        prepMins: 10,
        cookMins: 30,
        difficulty: 'easy' as const,
        ingredients: [
            { name: 'White yam', quantity: '1', unit: 'kg' },
            { name: 'Water', quantity: '500', unit: 'ml' },
            { name: 'Salt', quantity: '1', unit: 'pinch', notes: 'Optional' },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Peel and cut yam into chunks. Rinse well under cold water.' },
            { stepNumber: 2, instruction: 'Boil in salted water for 20–25 minutes until completely soft and a fork pierces through easily.' },
            { stepNumber: 3, instruction: 'Drain and transfer to a mortar. Pound with a pestle, adding small amounts of hot water as needed.' },
            { stepNumber: 4, instruction: 'Continue pounding and folding until completely smooth with no lumps — about 10 minutes.' },
            { stepNumber: 5, instruction: 'Shape into balls and serve immediately with your choice of soup.' },
        ],
    },
    {
        name: 'Moi Moi',
        category: 'Side Dish',
        description: 'A steamed bean pudding made from blended peeled black-eyed peas, peppers, and spices. Often includes fish, egg, or corned beef filling.',
        servings: 8,
        prepMins: 40,
        cookMins: 45,
        difficulty: 'medium' as const,
        ingredients: [
            { name: 'Black-eyed peas', quantity: '2', unit: 'cups' },
            { name: 'Red bell pepper', quantity: '1', unit: 'large' },
            { name: 'Scotch bonnet pepper', quantity: '1', unit: 'piece' },
            { name: 'Onion', quantity: '1', unit: 'medium' },
            { name: 'Vegetable oil', quantity: '4', unit: 'tbsp' },
            { name: 'Crayfish (ground)', quantity: '1', unit: 'tbsp' },
            { name: 'Seasoning cubes', quantity: '2', unit: 'pieces' },
            { name: 'Salt', quantity: '1', unit: 'tsp' },
            { name: 'Hard boiled eggs (halved)', quantity: '4', unit: 'pieces', notes: 'Optional filling' },
            { name: 'Canned tuna or sardines', quantity: '200', unit: 'g', notes: 'Optional filling' },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Soak black-eyed peas in water for 30 minutes. Rub between palms to remove skins. Rinse until water is clear.' },
            { stepNumber: 2, instruction: 'Blend peeled beans with bell pepper, scotch bonnet, onion, and a little water until very smooth.' },
            { stepNumber: 3, instruction: 'Pour batter into a bowl. Add oil, crayfish, seasoning cubes, and salt. Mix well.' },
            { stepNumber: 4, instruction: 'Grease foil cups, banana leaves, or ramekins. Fill halfway with batter.' },
            { stepNumber: 5, instruction: 'Add a piece of egg or fish filling to each cup, then cover with more batter.' },
            { stepNumber: 6, instruction: 'Steam on medium heat for 40–45 minutes until firm and set. A skewer should come out clean.' },
        ],
    },
    {
        name: 'Chin Chin',
        category: 'Snack / Street Food',
        description: 'Crunchy deep-fried Nigerian snack made from a sweetened dough. A beloved treat at parties and as an everyday snack.',
        servings: 10,
        prepMins: 30,
        cookMins: 30,
        difficulty: 'easy' as const,
        ingredients: [
            { name: 'Plain flour', quantity: '4', unit: 'cups' },
            { name: 'Sugar', quantity: '6', unit: 'tbsp' },
            { name: 'Butter or margarine', quantity: '4', unit: 'tbsp' },
            { name: 'Eggs', quantity: '2', unit: 'large' },
            { name: 'Milk', quantity: '100', unit: 'ml' },
            { name: 'Nutmeg', quantity: '0.5', unit: 'tsp' },
            { name: 'Baking powder', quantity: '1', unit: 'tsp' },
            { name: 'Salt', quantity: '0.5', unit: 'tsp' },
            { name: 'Vegetable oil', quantity: '500', unit: 'ml', notes: 'For deep frying' },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Combine flour, sugar, baking powder, nutmeg, and salt in a large bowl.' },
            { stepNumber: 2, instruction: 'Rub butter into the flour mixture until it resembles breadcrumbs.' },
            { stepNumber: 3, instruction: 'Beat eggs and milk together, then gradually mix into the flour to form a firm dough.' },
            { stepNumber: 4, instruction: 'Roll dough to about 3mm thickness on a floured surface. Cut into small strips or shapes.' },
            { stepNumber: 5, instruction: 'Heat oil to 160°C. Fry chin chin in batches for 5–7 minutes until golden brown, stirring occasionally.' },
            { stepNumber: 6, instruction: 'Drain on paper towels and allow to cool completely before storing in an airtight container.' },
        ],
    },
];

function seed(): void {
    console.log('[Seed] Inserting Nigerian recipes...');
    for (const recipe of recipes) {
        const id = createRecipe(recipe);
        console.log(`  [${id}] ${recipe.name}`);
    }
    console.log(`[Seed] Done — ${recipes.length} recipes inserted.`);
    closeDb();
}

seed();